const formData = {
   "metadata":{
      "device_id":"iPad_D03C2163-0D3F-4761-94BA-D58EAC41E5CA",
      "user_id":null,
      "username":"iPad-mini_Facilities1",
      "submitted_at":"2023-03-06 10:28:20 -08:00",
      "received_at":"2023-03-06 18:28:21 +00:00",
      "submission_id":"78644923",
      "device_submission_identifier":"F8D3A1DF-21D0-4649-9370-CE91C7378754",
      "submission_counter":"1609",
      "author_identifier":"iPad_D03C2163-0D3F-4761-94BA-D58EAC41E5CA",
      "form_name":"Facilities Daily Rounds",
      "form_namespace":"http://www.devicemagic.com/xforms/48490710-47f7-0136-36da-22000b280cc4",
      "form_version":"1.79"
   },
   "answers":{
      "Date":{
         "value":"2023-03-06"
      },
      "Technician":{
         "value":"Rob"
      },
      "Generator_Room":{
         "values":[
            {
               "Time":{
                  "value":"09:18:00"
               },
               "Generator_Name":{
                  "value":"Gen A"
               },
               "Fuel_meter__L_":{
                  "value":571990
               },
               "Generator_status":{
                  "value":"Off"
               },
               "Number_of_starts":{
                  "value":416
               },
               "Engine_hours":{
                  "value":1228.8
               },
               "Next_oil_change__h_":{
                  "value":1475
               },
               "Hours_until_next_oil_change":{
                  "value":246.2
               },
               "Next_heat_exchange_cleaning__h_":{
                  "value":1020
               },
               "Hours_until_next_heat_exchange_cleaning":{
                  "value":-208.8
               },
               "Next_fuel_filter_change__h_":{
                  "value":1520
               },
               "Hours_until_next_fuel_filter_change":{
                  "value":291.2
               },
               "Checked_oil_":{
                  "value":true
               },
               "Diesel_day_tank_gauge_level__in_":{
                  "value":26
               }
            }
         ]
      },
      "Bunkhouse_Fuel_Dispenser":{
         "values":[
            {
               "Time":{
                  "value":"09:20:00"
               },
               "Fuel_dispenser_containment_pans_inspected_":{
                  "value":true
               }
            }
         ]
      },
      "Boiler_Room":{
         "values":[
            {
               "Time":{
                  "value":"09:21:00"
               },
               "Fuel_meter__L_":{
                  "value":72379.4
               },
               "Glycol_tank_level__US_gal_":{
                  "value":18
               },
               "Glycol_tank_pressure__Psi_":{
                  "value":15
               },
               "Line_gauge_1_pressure__Psi_":{
                  "value":37
               },
               "Line_gauge_2_pressure__Psi_":{
                  "value":25
               },
               "Line_temperature__F_":{
                  "value":150
               },
               "Line_pressure__Psi_":{
                  "value":25
               },
               "Left_boiler_temperature__F_":{
                  "value":150
               },
               "Left_boiler_pressure__Psi_":{
                  "value":20
               },
               "Is_the_left_boiler_in_lockout_":{
                  "value":false
               },
               "Right_boiler_temperature__F_":{
                  "value":85
               },
               "Right_boiler_pressure__Psi_":{
                  "value":0
               },
               "Is_the_right_boiler_in_lockout_":{
                  "value":false
               },
               "General_line_temperature__F_":{
                  "value":150
               },
               "Calvert_pump_status":{
                  "value":"On"
               },
               "Calvert_pump_flow_rate__GPM_":{
                  "value":10
               },
               "Calvert_pump_power_consumption__W_":{
                  "value":43
               },
               "Headquarters_pump_status":{
                  "value":"On"
               },
               "Headquarters_pump_flow_rate__GPM_":{
                  "value":4
               },
               "Headquarters_pump_power_consumption__W_":{
                  "value":27
               },
               "Diesel_day_tank_gauge_level__in_":{
                  "value":20
               }
            }
         ]
      },
      "Water_Treatment":{
         "values":[
            {
               "Time":{
                  "value":"09:22:00"
               },
               "UV_dose_1_status":{
                  "value":"Green"
               },
               "UV_dose_2_status":{
                  "value":"Green"
               },
               "Chlorine_tank_level__L_":{
                  "value":80
               },
               "Water_meter_reading__cubic_feet_":{
                  "value":801119
               },
               "Tank_farm_status":{
                  "value":"Good"
               },
               "Air_dryer_crystal_colour":{
                  "value":"Blue"
               },
               "Ozone_generator_A_status":{
                  "value":"Ozone"
               },
               "Ozone_generator_A_flow__L_min_":{
                  "value":3
               },
               "Ozone_generator_B_status":{
                  "value":"Ozone"
               },
               "Ozone_generator_B_flow__L_min_":{
                  "value":3
               },
               "Ozone_generator_C_status":{
                  "value":"Ozone"
               },
               "Ozone_generator_C_flow__L_min_":{
                  "value":2.5
               },
               "Water_in_ozone_tank_barometer_":{
                  "value":true
               },
               "Ozone_alarm_status":{
                  "value":"Green"
               },
               "Number_of_people_on_site_":{
                  "value":2
               }
            }
         ]
      },
      "Dock":{
         "values":[
            {
               "Time":{
                  "value":"09:30:00"
               },
               "Fuel_dispenser_containment_pans_inspected_":{
                  "value":true
               },
               "Have_you_checked_the_boats_":{
                  "value":true
               }
            }
         ]
      },
      "Darby_Lab":{
         "values":[
            {
               "Time":{
                  "value":"09:32:00"
               },
               "Pressure__Psi_":{
                  "value":22
               },
               "Glycol_tank_level__US_gal_":{
                  "value":3.8
               },
               "Glycol_tank_pressure__Psi_":{
                  "value":0
               }
            }
         ]
      },
      "Main_Lodge":{
         "values":[
            {
               "Time":{
                  "value":"09:33:00"
               },
               "Boiler_pressure__Psi_":{
                  "value":20
               },
               "Pump_1_status":{
                  "value":"On"
               },
               "Pump_1_flow_rate__GPM_":{
                  "value":13
               },
               "Pump_1_power_consumption__W_":{
                  "value":43
               },
               "Pump_2_status":{
                  "value":"On"
               },
               "Pump_2_flow_rate__GPM_":{
                  "value":10
               },
               "Pump_2_power_consumption__W_":{
                  "value":43
               },
               "Glycol_tank_level__US_gal_":{
                  "value":3
               },
               "Glycol_tank_pressure__Psi_":{
                  "value":21
               }
            }
         ]
      },
      "Britco_Lodge":{
         "values":[
            {
               "Time":{
                  "value":"10:24:00"
               },
               "Top_gauge_temperature__F_":{
                  "value":130
               },
               "Bottom_gauge_temperature__F_":{
                  "value":120
               },
               "Bottom_gauge_pressure__Psi_":{
                  "value":20
               },
               "Glycol_tank_level__US_gal_":{
                  "value":2.8
               },
               "Glycol_tank_pressure__Psi_":{
                  "value":21
               }
            }
         ]
      },
      "Sewage_Treatment":{
         "values":[
            {
               "Time":{
                  "value":"10:26:00"
               },
               "Timer_enabled_float__EN_":{
                  "value":"Off"
               },
               "Low_level_float__LL_":{
                  "value":"On"
               },
               "Total_zone_dose__L_":{
                  "value":95967
               },
               "Zone_1_dose__L_":{
                  "value":23174
               },
               "Zone_2_dose__L_":{
                  "value":24905
               },
               "Zone_3_dose__L_":{
                  "value":23834
               },
               "Zone_4_dose__L_":{
                  "value":21318
               },
               "Zone_flush_dose__L_":{
                  "value":2723
               },
               "Filter_flush_dose__L_":{
                  "value":0
               },
               "Are_there_any_new_alarms_":{
                  "value":false
               },
               "Currently_flushing_":{
                  "value":false
               }
            }
         ]
      },
      "Big_Greenhouse":{
         "values":[
            {
               "Time":{
                  "value":"10:27:00"
               },
               "Boiler_supply_temperature__F_":{
                  "value":158
               },
               "Outdoor_temperature__F_":{
                  "value":39
               },
               "Mixing_supply_temperature__F_":{
                  "value":87
               },
               "Demand_for_heat_":{
                  "value":false
               }
            }
         ]
      }
   }
}

function nestedLoop(obj) {
   const res = [];
   var tmpKey = [];
   function recurse(obj, current) {
       for (const key in obj) {
           let value = obj[key];
           if(value != undefined) {
               if (value && typeof value === 'object') {
                  console.log(`${key}`)
                  tmpKey.push(`${key}`)
                  recurse(value, key);
               } else {
                  if (current != "metadata"){
                     if (tmpKey[1] == "values"){
                        console.log(tmpKey[0])
                        let tmpVal = {"Name": current, "Value": value}
                        res.push(tmpVal);
                        tmpKey = [];
                     }
                     

                  }
               }
           }
       }
   }
   recurse(obj);
   //return res;
   console.log(res);
}
nestedLoop(formData);
